# ==============================================================================
# ODOO IMPORT FILE SPLITTER
# Version: 1.2
# Purpose: Splits large CSV files into smaller chunks for easier import.
# ==============================================================================
import csv
import os

# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================
# --- Set the number of records you want in each smaller file ---
CHUNK_SIZE = 100

# --- These are the files generated by the Gold Master script ---
INPUT_FILES = [
    'Final_Import_Customers.csv',
    'Final_Import_Properties.csv',
    'Final_Import_SalesOrders.csv'
]

# ==============================================================================
# 2. SPLITTING ENGINE
# ==============================================================================

def split_csv(input_file, chunk_size):
    """
    Reads a CSV file and splits it into multiple smaller CSV files.
    
    Args:
        input_file (str): The path to the source CSV file.
        chunk_size (int): The maximum number of rows per smaller file.
    """
    if not os.path.exists(input_file):
        print(f"[WARNING] File not found: {input_file}. Skipping.")
        return

    try:
        with open(input_file, mode='r', encoding='utf-8', newline='') as f_in:
            reader = csv.reader(f_in)
            
            # Read the header row, it will be added to every chunk file.
            header = next(reader)
            
            file_count = 1
            chunk_rows = []
            
            for row in reader:
                chunk_rows.append(row)
                if len(chunk_rows) >= chunk_size:
                    # Construct the output filename
                    base, ext = os.path.splitext(input_file)
                    output_filename = f"{base}_part_{file_count}{ext}"
                    
                    # Write the current chunk to a new file
                    with open(output_filename, mode='w', encoding='utf-8', newline='') as f_out:
                        writer = csv.writer(f_out)
                        writer.writerow(header)
                        writer.writerows(chunk_rows)
                        print(f"  [WRITE] Created {output_filename} with {len(chunk_rows)} records.")
                        
                    # Reset for the next chunk
                    file_count += 1
                    chunk_rows = []
            
            # Write any remaining rows to a final file
            if chunk_rows:
                base, ext = os.path.splitext(input_file)
                output_filename = f"{base}_part_{file_count}{ext}"
                with open(output_filename, mode='w', encoding='utf-8', newline='') as f_out:
                    writer = csv.writer(f_out)
                    writer.writerow(header)
                    writer.writerows(chunk_rows)
                    print(f"  [WRITE] Created {output_filename} with {len(chunk_rows)} records.")

        print(f"[SUCCESS] Finished splitting {input_file}.\n")
        
    except Exception as e:
        print(f"[ERROR] Could not process file {input_file}: {e}")

# ==============================================================================
# 3. EXECUTION
# ==============================================================================

if __name__ == '__main__':
    print("[START] Beginning CSV file splitting process.")
    print(f"Target chunk size: {CHUNK_SIZE} records per file.\n")
    
    for filename in INPUT_FILES:
        print(f"Processing {filename}...")
        split_csv(filename, CHUNK_SIZE)
        
    print("[COMPLETE] All files have been processed.")